# Generated by Django 4.1.7 on 2023-04-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ingredient Name')),
                ('exp_date', models.DateField(verbose_name='Ingredient Exp_date')),
                ('quantity', models.FloatField(verbose_name='Ingredient Quantity')),
                ('measure_unit', models.CharField(max_length=10, verbose_name='Ingredient Measure_unit')),
                ('price', models.FloatField(verbose_name='Ingredient Price')),
                ('obs', models.TextField(blank=True, verbose_name='Ingredient Obs')),
            ],
        ),
    ]
