# Generated by Django 4.1.7 on 2023-04-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0004_alter_table_options_rename_name_table_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do prato')),
                ('price', models.FloatField(verbose_name='Preço de venda')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('ingredients', models.ManyToManyField(to='Malo_App.ingredient')),
            ],
        ),
        migrations.DeleteModel(
            name='Cardapio',
        ),
        migrations.AddField(
            model_name='category',
            name='dishes',
            field=models.ManyToManyField(to='Malo_App.dish'),
        ),
    ]
