# Generated by Django 4.1.7 on 2023-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0007_alter_category_dishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('descricao', models.CharField(default='Mesa', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
