# Generated by Django 4.2 on 2023-04-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0008_mesa_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientQuant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ingrediente')),
                ('quantity', models.FloatField(verbose_name='Quantidade')),
                ('measure_unit', models.CharField(max_length=10, verbose_name='Unidade de medida')),
            ],
        ),
    ]
