# Generated by Django 4.1.7 on 2023-05-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0013_alter_ingredient_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='dishes',
        ),
    ]
