# Generated by Django 4.1.7 on 2023-05-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0018_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
