# Generated by Django 4.1.7 on 2023-05-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0020_garcom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dish',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Preço Total'),
        ),
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Malo_App.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Malo_App.order')),
            ],
        ),
    ]
