# Generated by Django 4.1.7 on 2023-05-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0021_remove_order_dish_order_total_price_orderdish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total_price_local',
        ),
    ]
