# Generated by Django 4.1.7 on 2023-05-14 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0023_alter_order_total_price_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Malo_App.mesa'),
        ),
    ]
