# Generated by Django 4.2 on 2023-05-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0024_alter_order_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='garcom',
            name='status',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Login'),
        ),
    ]
