# Generated by Django 4.2 on 2023-05-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0026_alter_garcom_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garcom',
            name='status',
        ),
    ]
