# Generated by Django 4.1.7 on 2023-05-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0027_remove_garcom_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='nome')),
                ('exp_employers', models.FloatField(verbose_name='Despesas funcionarios')),
                ('tips', models.FloatField(verbose_name='servico')),
                ('billing', models.FloatField(verbose_name='faturamento')),
                ('feedstock', models.FloatField(verbose_name='insumos')),
            ],
        ),
    ]
