# Generated by Django 4.1.7 on 2023-05-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0028_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='exp_employers',
            new_name='exp_employees',
        ),
    ]
