# Generated by Django 4.2 on 2023-05-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0030_alter_dishingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garcom',
            name='salario',
            field=models.FloatField(verbose_name='Salário'),
        ),
    ]
