# Generated by Django 4.1.7 on 2023-04-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='exp_date',
            field=models.DateField(verbose_name='Data de validade'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure_unit',
            field=models.CharField(max_length=10, verbose_name='Unidade de medida'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Ingrediente'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='obs',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(verbose_name='Preço de compra(total)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(verbose_name='Quantidade'),
        ),
    ]
