# Generated by Django 4.1.7 on 2023-04-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0003_cardapio_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
        migrations.RenameField(
            model_name='table',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='table',
            name='quantity',
        ),
    ]
