# Generated by Django 4.2 on 2023-04-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0006_alter_category_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='Malo_App.dish'),
        ),
    ]
