# Generated by Django 3.2.12 on 2023-04-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0008_mesa_delete_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='exp_date',
            field=models.DateField(null=True, verbose_name='Data de validade'),
        ),
    ]
