# Generated by Django 4.2 on 2023-04-15 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0009_ingredientquant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ingrediente')),
                ('quantity', models.FloatField(verbose_name='Quantidade')),
                ('measure_unit', models.CharField(max_length=10, verbose_name='Unidade de medida')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Malo_App.dish')),
            ],
        ),
        migrations.DeleteModel(
            name='IngredientQuant',
        ),
    ]
