# Generated by Django 4.2 on 2023-04-16 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0010_dishingredient_delete_ingredientquant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
    ]
