# Generated by Django 3.2.12 on 2023-04-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0009_alter_ingredient_exp_date'),
        ('Malo_App', '0011_remove_dish_ingredients'),
    ]

    operations = [
    ]
