# Generated by Django 4.2 on 2023-05-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Malo_App', '0022_rename_total_price_order_total_price_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price_local',
            field=models.FloatField(default=0),
        ),
    ]
